/**
 * Elite US Pack Llama Reference Panel
 * Composite profiles based on well-documented Ccara / classic pack lines,
 * PLTA Master Packers, and published structural guidelines (NACA, Middle Earth,
 * Backcountry Logistics, JNK, Burns Trailblazers, Black Mountain, etc.).
 *
 * Targets represent elite athletic pack conformation — not pet or wool types.
 * Ideal pack height band: 43–46" at withers (soundness declines above ~48").
 */

export const ELITE_PANEL = [
  {
    name: "Isle Eagle",
    sex: "male",
    farm: "JNK Llama Farm (WA)",
    notes: "PLTA Master Packer; ALSA Breeder Elite; multi-national driving champ",
    witherHeight: 45.5,
    legOverGirth: 3.5,
    chestWidth: 4.5,
    neckToBack: 0.68,
    backToHeight: 0.52,
    hipOffset: 0,
    cannon: 5.9,
    weight: 311,
    pastern: "upright",
    stance: "narrow",
    muscling: "excellent",
    topline: "level",
    flank: "cut-high",
  },
  {
    name: "MPL Anders Tobias",
    sex: "male",
    farm: "JNK Llama Farm (WA)",
    notes: "Classic lines; PLTA Master Packer; packed ~90 lb until injury",
    witherHeight: 44.5,
    legOverGirth: 3.2,
    chestWidth: 4.8,
    neckToBack: 0.66,
    backToHeight: 0.53,
    hipOffset: 0,
    cannon: 5.85,
    weight: 300,
    pastern: "upright",
    stance: "narrow",
    muscling: "excellent",
    topline: "level",
    flank: "cut-high",
  },
  {
    name: "The Special Edition",
    sex: "male",
    farm: "Burns Llama Trailblazers",
    notes: "PLTA Master Packer; string-tail position; ALSA performance champ",
    witherHeight: 46.0,
    legOverGirth: 3.4,
    chestWidth: 4.6,
    neckToBack: 0.67,
    backToHeight: 0.51,
    hipOffset: -0.5,
    cannon: 6.0,
    weight: 324,
    pastern: "upright",
    stance: "narrow",
    muscling: "excellent",
    topline: "level",
    flank: "cut-high",
  },
  {
    name: "Hi Trl Commander Spock",
    sex: "male",
    farm: "Hi Trl / Ccara sire lines",
    notes: "Certified Ccara; prolific commercial pack stud",
    witherHeight: 47.0,
    legOverGirth: 3.6,
    chestWidth: 4.4,
    neckToBack: 0.7,
    backToHeight: 0.5,
    hipOffset: 0,
    cannon: 6.1,
    weight: 324,
    pastern: "upright",
    stance: "narrow",
    muscling: "excellent",
    topline: "level",
    flank: "cut-high",
  },
  {
    name: "Cheyenne",
    sex: "female",
    farm: "Black Mountain Pack Llamas (CA)",
    notes: "Ccara certified; 46¾\"; ALSA National GCH light wool classic",
    witherHeight: 46.75,
    legOverGirth: 3.3,
    chestWidth: 4.7,
    neckToBack: 0.67,
    backToHeight: 0.52,
    hipOffset: 0,
    cannon: 5.7,
    weight: 342,
    pastern: "upright",
    stance: "narrow",
    muscling: "good",
    topline: "level",
    flank: "cut-high",
  },
  {
    name: "Maybelline",
    sex: "female",
    farm: "Black Mountain Pack Llamas (CA)",
    notes: "Ccara certified; 48\"; dam of proven working offspring",
    witherHeight: 48.0,
    legOverGirth: 3.5,
    chestWidth: 4.9,
    neckToBack: 0.66,
    backToHeight: 0.51,
    hipOffset: 0,
    cannon: 5.8,
    weight: 354,
    pastern: "upright",
    stance: "narrow",
    muscling: "good",
    topline: "level",
    flank: "cut-high",
  },
  {
    name: "Spot's Ragnar",
    sex: "male",
    farm: "Backcountry Logistics",
    notes: "Passed NACA Ccara screen; ILR Ccara designation",
    witherHeight: 45.0,
    legOverGirth: 3.0,
    chestWidth: 5.0,
    neckToBack: 0.67,
    backToHeight: 0.53,
    hipOffset: 0,
    cannon: 5.9,
    weight: 301,
    pastern: "upright",
    stance: "narrow",
    muscling: "excellent",
    topline: "level",
    flank: "cut-high",
  },
  {
    name: "Lost Creek Atlas",
    sex: "male",
    farm: "Lost Creek Llamas",
    notes: "Classic performance selection; soundness-over-height philosophy",
    witherHeight: 43.5,
    legOverGirth: 3.1,
    chestWidth: 4.3,
    neckToBack: 0.68,
    backToHeight: 0.54,
    hipOffset: 0,
    cannon: 5.75,
    weight: 296,
    pastern: "upright",
    stance: "narrow",
    muscling: "excellent",
    topline: "level",
    flank: "cut-high",
  },
  {
    name: "Lost Creek Fennel",
    sex: "female",
    farm: "Lost Creek Llamas",
    notes: "Compact elite packer type — proves height isn't everything",
    witherHeight: 42.75,
    legOverGirth: 2.8,
    chestWidth: 4.5,
    neckToBack: 0.65,
    backToHeight: 0.55,
    hipOffset: 0.25,
    cannon: 5.7,
    weight: 294,
    pastern: "upright",
    stance: "narrow",
    muscling: "good",
    topline: "level",
    flank: "cut-high",
  },
  {
    name: "Middle Earth Ridge Runner",
    sex: "male",
    farm: "Middle Earth Llama Ranch",
    notes: "Structural guideline exemplar: legs > girth, chest < 6\"",
    witherHeight: 44.0,
    legOverGirth: 3.4,
    chestWidth: 4.2,
    neckToBack: 0.67,
    backToHeight: 0.52,
    hipOffset: -0.25,
    cannon: 5.8,
    weight: 304,
    pastern: "upright",
    stance: "narrow",
    muscling: "excellent",
    topline: "level",
    flank: "cut-high",
  },
  {
    name: "Middle Earth Packwise",
    sex: "male",
    farm: "Middle Earth Llama Ranch",
    notes: "Tall-narrow athletic frame with obvious pectoral muscling",
    witherHeight: 45.5,
    legOverGirth: 3.7,
    chestWidth: 4.0,
    neckToBack: 0.69,
    backToHeight: 0.5,
    hipOffset: 0,
    cannon: 5.85,
    weight: 304,
    pastern: "upright",
    stance: "narrow",
    muscling: "excellent",
    topline: "level",
    flank: "cut-high",
  },
  {
    name: "Wilderness Ridge Sarge",
    sex: "male",
    farm: "Wilderness Ridge Trail Llamas",
    notes: "Commercial high-endurance packer; multi-day payload work",
    witherHeight: 48.5,
    legOverGirth: 4.0,
    chestWidth: 4.6,
    neckToBack: 0.7,
    backToHeight: 0.49,
    hipOffset: 0,
    cannon: 6.2,
    weight: 342,
    pastern: "upright",
    stance: "narrow",
    muscling: "excellent",
    topline: "level",
    flank: "cut-high",
  },
  {
    name: "Wilderness Ridge Milo",
    sex: "male",
    farm: "Wilderness Ridge Trail Llamas",
    notes: "Working-class commercial packer meeting trail criteria",
    witherHeight: 45.0,
    legOverGirth: 3.2,
    chestWidth: 4.8,
    neckToBack: 0.66,
    backToHeight: 0.52,
    hipOffset: 0,
    cannon: 5.95,
    weight: 311,
    pastern: "upright",
    stance: "narrow",
    muscling: "excellent",
    topline: "level",
    flank: "cut-high",
  },
  {
    name: "NACA Screen Benchmark A",
    sex: "female",
    farm: "NACA screening composite",
    notes: "Modeled on 45+/50 Ccara pass: 2\"+ leg clearance, level back",
    witherHeight: 44.0,
    legOverGirth: 2.5,
    chestWidth: 5.0,
    neckToBack: 0.67,
    backToHeight: 0.53,
    hipOffset: 0,
    cannon: 5.75,
    weight: 330,
    pastern: "upright",
    stance: "narrow",
    muscling: "good",
    topline: "level",
    flank: "cut-high",
  },
  {
    name: "NACA Screen Benchmark B",
    sex: "male",
    farm: "NACA screening composite",
    notes: "Near-max screen traits: athletic stance, strong pasterns",
    witherHeight: 46.0,
    legOverGirth: 3.5,
    chestWidth: 4.5,
    neckToBack: 0.68,
    backToHeight: 0.51,
    hipOffset: -0.5,
    cannon: 6.0,
    weight: 309,
    pastern: "upright",
    stance: "narrow",
    muscling: "excellent",
    topline: "level",
    flank: "cut-high",
  },
  {
    name: "Rocky Mountain Trail King",
    sex: "male",
    farm: "Rocky Mountain pack programs",
    notes: "Long-stride commercial string animal; strong front-leg anchors",
    witherHeight: 46.5,
    legOverGirth: 3.6,
    chestWidth: 4.4,
    neckToBack: 0.69,
    backToHeight: 0.5,
    hipOffset: 0,
    cannon: 6.05,
    weight: 315,
    pastern: "upright",
    stance: "narrow",
    muscling: "excellent",
    topline: "level",
    flank: "cut-high",
  },
  {
    name: "Sierra Crest Vanguard",
    sex: "male",
    farm: "High Sierra outfitter lines",
    notes: "Multi-day High Sierra packing; A-shaped saddle-holding back",
    witherHeight: 45.25,
    legOverGirth: 3.3,
    chestWidth: 4.6,
    neckToBack: 0.67,
    backToHeight: 0.52,
    hipOffset: 0,
    cannon: 5.9,
    weight: 318,
    pastern: "upright",
    stance: "narrow",
    muscling: "excellent",
    topline: "level",
    flank: "cut-high",
  },
  {
    name: "Cascades Ironclad",
    sex: "male",
    farm: "Pacific NW classic pack lines",
    notes: "Heavy-bone power packer style (6¼\" cannon class)",
    witherHeight: 47.5,
    legOverGirth: 3.4,
    chestWidth: 5.0,
    neckToBack: 0.65,
    backToHeight: 0.51,
    hipOffset: 0.25,
    cannon: 6.25,
    weight: 360,
    pastern: "upright",
    stance: "narrow",
    muscling: "excellent",
    topline: "level",
    flank: "cut-high",
  },
  {
    name: "Yellowstone Windrift",
    sex: "female",
    farm: "Northern Rockies pack stock",
    notes: "Rangy endurance type with long upper-leg leverage",
    witherHeight: 44.75,
    legOverGirth: 3.8,
    chestWidth: 4.1,
    neckToBack: 0.7,
    backToHeight: 0.5,
    hipOffset: -0.25,
    cannon: 5.8,
    weight: 329,
    pastern: "springy",
    stance: "narrow",
    muscling: "good",
    topline: "level",
    flank: "cut-high",
  },
  {
    name: "Wasatch Summit",
    sex: "male",
    farm: "Intermountain pack lines",
    notes: "Withers ≥ hips; packs with minimal breeching need",
    witherHeight: 45.0,
    legOverGirth: 3.2,
    chestWidth: 4.7,
    neckToBack: 0.66,
    backToHeight: 0.52,
    hipOffset: -0.75,
    cannon: 5.85,
    weight: 310,
    pastern: "upright",
    stance: "narrow",
    muscling: "excellent",
    topline: "level",
    flank: "cut-high",
  },
  {
    name: "Appalachian Ridgewalker",
    sex: "female",
    farm: "Eastern trail pack programs",
    notes: "Compact athletic packer; under-6\" chest; upright pasterns",
    witherHeight: 43.25,
    legOverGirth: 2.9,
    chestWidth: 4.9,
    neckToBack: 0.65,
    backToHeight: 0.54,
    hipOffset: 0,
    cannon: 5.7,
    weight: 322,
    pastern: "upright",
    stance: "narrow",
    muscling: "good",
    topline: "level",
    flank: "cut-high",
  },
  {
    name: "Colorado Divide",
    sex: "male",
    farm: "Colorado pack llama programs",
    notes: "Elite hip-stifle angulation for steep-climb thrust",
    witherHeight: 46.25,
    legOverGirth: 3.5,
    chestWidth: 4.5,
    neckToBack: 0.68,
    backToHeight: 0.51,
    hipOffset: 0,
    cannon: 6.0,
    weight: 309,
    pastern: "upright",
    stance: "narrow",
    muscling: "excellent",
    topline: "level",
    flank: "cut-high",
  },
];

/**
 * Sex-specific size bands for elite pack stock.
 * Females run smaller; males taller/heavier-boned. Proportions stay strict for both.
 */
export const SEX_STANDARDS = {
  male: {
    label: "male",
    witherHeight: {
      idealMin: 43.5,
      idealMax: 47.0,
      softMax: 48.5,
      failBelow: 40.5,
      failAbove: 52,
      center: 45.25,
    },
    cannon: { idealMin: 5.6, idealMax: 6.25 },
    // lbs per inch of wither height (Middle Earth–style lean pack ratios)
    weightRatio: { idealMin: 6.5, idealMax: 7.7, center: 7.05 },
    weightAbs: { softMax: 360, hardMax: 400 },
    legElite: 3.1,
    chestEliteMax: 5.0,
    minUtilityHeight: 41.5,
    maxSoundHeight: 50,
  },
  female: {
    label: "female",
    witherHeight: {
      idealMin: 42.0,
      idealMax: 45.5,
      softMax: 47.0,
      failBelow: 39.5,
      failAbove: 50,
      center: 43.75,
    },
    cannon: { idealMin: 5.2, idealMax: 5.9 },
    weightRatio: { idealMin: 7.0, idealMax: 8.0, center: 7.4 },
    weightAbs: { softMax: 340, hardMax: 380 },
    legElite: 2.8,
    chestEliteMax: 4.9,
    minUtilityHeight: 40.0,
    maxSoundHeight: 49,
  },
};

/** Elite panel statistic targets used for picky comparison */
export function computeEliteTargets(panel = ELITE_PANEL, sex = null) {
  const avg = (arr) => (arr.length ? arr.reduce((a, b) => a + b, 0) / arr.length : 0);
  const scoped = sex ? panel.filter((p) => p.sex === sex) : panel;
  const use = scoped.length ? scoped : panel;
  const std = SEX_STANDARDS[sex] || null;
  const sorted = [...use].map((p) => p.witherHeight).sort((a, b) => a - b);
  const mid = Math.floor(sorted.length / 2);

  return {
    sex: sex || "all",
    count: use.length,
    witherHeight: {
      mean: avg(use.map((p) => p.witherHeight)),
      median: sorted.length % 2 ? sorted[mid] : (sorted[mid - 1] + sorted[mid]) / 2,
      min: sorted[0],
      max: sorted[sorted.length - 1],
      idealMin: std?.witherHeight.idealMin ?? 43,
      idealMax: std?.witherHeight.idealMax ?? 46.5,
      softMax: std?.witherHeight.softMax ?? 48,
      failBelow: std?.witherHeight.failBelow ?? 40,
      failAbove: std?.witherHeight.failAbove ?? 52,
      center: std?.witherHeight.center ?? 44.75,
    },
    legOverGirth: {
      mean: avg(use.map((p) => p.legOverGirth)),
      minAcceptable: 2.0,
      elite: std?.legElite ?? 3.0,
    },
    chestWidth: {
      mean: avg(use.map((p) => p.chestWidth)),
      maxAcceptable: 6.0,
      eliteMax: std?.chestEliteMax ?? 5.0,
    },
    neckToBack: {
      mean: avg(use.map((p) => p.neckToBack)),
      ideal: 2 / 3,
      tol: 0.06,
    },
    backToHeight: {
      mean: avg(use.map((p) => p.backToHeight)),
      eliteMax: 0.55,
    },
    hipOffset: {
      mean: avg(use.map((p) => p.hipOffset)),
    },
    cannon: {
      mean: avg(use.map((p) => p.cannon)),
      idealMin: std?.cannon.idealMin ?? 5.5,
      idealMax: std?.cannon.idealMax ?? 6.25,
    },
    weight: {
      mean: avg(use.map((p) => p.weight)),
      ratioMin: std?.weightRatio.idealMin ?? 6.5,
      ratioMax: std?.weightRatio.idealMax ?? 7.8,
      ratioCenter: std?.weightRatio.center ?? 7.1,
      softMax: std?.weightAbs.softMax ?? 360,
      hardMax: std?.weightAbs.hardMax ?? 400,
    },
    minUtilityHeight: std?.minUtilityHeight ?? 41,
    maxSoundHeight: std?.maxSoundHeight ?? 50,
  };
}

export function getTargetsForSex(sex) {
  const normalized = sex === "female" ? "female" : "male";
  return computeEliteTargets(ELITE_PANEL, normalized);
}

export function panelForSex(sex) {
  const normalized = sex === "female" ? "female" : "male";
  const same = ELITE_PANEL.filter((p) => p.sex === normalized);
  return same.length ? same : ELITE_PANEL;
}
